// AUTO-GENERATED by scripts/build-sidebar-map.js — do not edit.
// Maps doc slugs (relative to content/docs/, without .mdx extension) to
// the `displayed_sidebar` frontmatter value. Consumed by getSidebarForPathname.

export const sidebarAssignments: Record<string, string> = {}
